FROM ruby:4.0-slim

RUN apt-get update && apt-get install -y \
      build-essential \
      git \
    && rm -rf /var/lib/apt/lists/*

RUN git config --global --add safe.directory '*'

WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install
