require "json"
require "tempfile"

module OPilot
  module Helpers
    # Paths and records under .opilot/: where per-WP, per-change and per-incident
    # state lives, and the ItemState that carries it through a run.

    # Per-WP state lives under .opilot/work_packages/<op_host>/<id>/ —
    # namespaced by the OpenProject instance (see Context#op_host) so different
    # instances don't collide. One source of truth for that path, used
    # everywhere instead of re-joining the literal.
    def self.items_dir(ctx)
      ctx.state_dir / "work_packages" / ctx.op_host
    end

    def self.item_dir(ctx, id)
      items_dir(ctx) / id.to_s
    end

    # Rewrite a host path under .opilot/ to its path inside the harness
    # container, where .opilot is mounted read-only at /state. A module function
    # as well as an instance method (#container_path) because OpPull writes
    # container paths into item.json and does not include Helpers.
    def self.state_container_path(ctx, host_path)
      host_path.to_s.sub(ctx.state_dir.to_s, ctx.state_container)
    end

    # The <id>/repos/<name>/ dirs under one work-package dir that hold a shipped
    # PR. One definition, because "what counts as a shipped PR dir" is asked both
    # of every work package (the gh-agent scan) and of one (`dev refresh`).
    def self.pr_dirs_in(item_dir)
      repos_dir = item_dir / "repos"
      return [] unless repos_dir.exist?
      repos_dir.children.select(&:directory?).sort
               .select { |d| file_has_content?(d / "pr_url.txt") }
    end

    # The same shape for the `pd` pipeline's per-change state, in its own
    # namespace (changes/ vs work_packages/) since a change id and a work-package
    # id are different things that could otherwise collide.
    def self.changes_dir(ctx)
      ctx.state_dir / "changes" / ctx.op_host
    end

    def self.change_dir(ctx, change_id)
      changes_dir(ctx) / change_id.to_s
    end

    # `./opilot appsignal`'s per-incident state. Namespaced by OpenProject host
    # for the reason items_dir is: wp_id.txt records a work package on ONE
    # instance, and incident #4711 means nothing on another. The app segment is
    # there because an incident number is only unique within one app.
    def self.incident_dir(ctx, app, number)
      ctx.state_dir / "appsignal" / ctx.op_host / slugify(app, fallback: "app") / number.to_s
    end

    # Filesystem-safe slug of a title. One implementation, because the rule (what
    # "&" becomes, what counts as a separator, hyphen trimming) has to be identical
    # everywhere: an attachment's directory name and the markdown link pointing at
    # it are generated by separate call sites, and a slug that differs by one
    # character between them silently produces a broken link.
    def self.slugify(str, fallback: "item", limit: 60)
      s = str.to_s.downcase.gsub("&", "and").gsub(/[^a-z0-9]+/, "-").gsub(/\A-+|-+\z/, "")
      s.empty? ? fallback : s[0, limit]
    end

    # A file exists and is non-empty — the "has real content" check used for
    # plans, PR descriptions, session ids, and shipped markers.
    def self.file_has_content?(path)
      path.exist? && path.size > 0
    end

    # Parse a JSON file, returning nil on any read/parse error. Callers add
    # their own `|| {}` / `|| []` fallback where they depend on one.
    def self.safe_json_read(path)
      JSON.parse(path.read)
    rescue StandardError
      nil
    end

    # Write JSON to `path` atomically (tempfile in the same dir, then rename),
    # so a crash mid-write never leaves a half-written cache. `name` is the
    # tempfile prefix. `pretty:` is for the files a human reads in a diff (the
    # `pd` pipeline commits tracker.json into the spec store) — they need the
    # same crash-safety as the machine-only caches, just not on one line.
    def self.write_json_atomic(path, data, name, pretty: false)
      tmp = Tempfile.new(name, path.dirname)
      tmp.write(pretty ? JSON.pretty_generate(data) : JSON.generate(data))
      tmp.close
      File.rename(tmp.path, path.to_s)
    rescue StandardError
      tmp&.unlink
      raise
    end

    # Per-WP working state: the shared paths under work_packages/<host>/<id>/ plus
    # the branch and the chosen target repos. PR-scoped artifacts (pr.md,
    # pr_url.txt, gh caches) live under <id>/repos/<name>/ since a WP may ship to
    # several repos — resolve them with the per-repo helpers below. Shared by both
    # runners (agent and the terminal fix/plan flow) via #state_for.
    ItemState = Struct.new(:item_id, :subject, :branch, :repos, :bases, :item_dir, :plan_file,
                           :item_file, :related_file, :target_repos_file,
                           :target_base_file, :options_file, :created_wps_file,
                           :session_file, keyword_init: true) do
      # Per-repo artifact directory (<id>/repos/<name>/), created on demand.
      def repo_dir(repo)
        dir = item_dir / "repos" / repo_name(repo)
        dir.mkpath
        dir
      end

      def pr_desc_file(repo); repo_dir(repo) / "pr.md"; end
      def pr_url_file(repo);  repo_dir(repo) / "pr_url.txt"; end

      # The plan gist URL, cached per-WP (not per-repo): plan.md is shared across
      # every repo a WP ships to, so all their PRs link the same gist.
      def gist_url_file; item_dir / "gist_url.txt"; end

      # Where one chat answer's artifacts are mirrored, keyed by the comment that
      # asked for them so two answers cannot overwrite each other.
      def artifact_dir(comment_at)
        dir = item_dir / "artifacts" / Helpers.slugify(comment_at, fallback: "chat")
        dir.mkpath
        dir
      end

      # The base branch this WP's PR targets in `repo`: the per-WP override the
      # user requested (target_base.json), else the repo's registry default. The
      # fix branch is both created from and the PR opened against this branch.
      def base_for(repo)
        (bases || {})[repo_name(repo)] || repo.base
      end

      private

      def repo_name(repo)
        repo.respond_to?(:name) ? repo.name : repo.to_s
      end
    end

    def safe_rm(*paths)
      paths.each do |path|
        path = Pathname(path)
        unless path.to_s.start_with?(@ctx.script_dir.to_s)
          $stderr.puts "BUG: safe_rm refusing unexpected path: #{path}"
          next
        end
        path.delete if path.exist?
      end
    end

    private

    def record_progress(id, branch, note)
      @ctx.progress_file.open("a") do |f|
        f.puts "#{Time.now.strftime("%Y-%m-%dT%H:%M")}|#{id}|#{branch}|#{note}"
      end
    end

    # Build the ItemState for a WP, creating its work_packages/<host>/<id>/ directory. The
    # target repos are loaded from target_repos.json (set once the LLM picks them
    # in the plan); until then the state defaults to the registry's default repo.
    def state_for(item_id, subject, type = nil)
      dir = Helpers.item_dir(@ctx, item_id)
      dir.mkpath
      ItemState.new(
        item_id:           item_id.to_s,
        subject:           subject.to_s,
        branch:            branch_slug(item_id, type.to_s, subject.to_s),
        repos:             target_repos_for(item_id),
        bases:             target_bases_for(item_id),
        item_dir:          dir,
        plan_file:         dir / "plan.md",
        item_file:         dir / "item.json",
        related_file:      dir / "related.json",
        target_repos_file: dir / "target_repos.json",
        target_base_file:  dir / "target_base.json",
        # The implementation options offered for this WP, written when a `ship`
        # plan call answers with the OPTIONS sentinel. Present means "opilot is
        # waiting for a number"; a chosen option leaves it in place, so the
        # reporter can read the list again after the prototype exists.
        options_file:      dir / "options.json",
        # Work packages `@opilot create wp` has already created FROM this one,
        # keyed by the trigger comment's timestamp. Written the moment a POST
        # succeeds: a work package can never be deleted, so a re-fired trigger
        # must find the record rather than create a second work package.
        created_wps_file:  dir / "created_wps.json",
        session_file:      dir / "session_id"
      )
    end

    # The Repo objects a WP targets, read from <id>/target_repos.json (an
    # array of registry names); unknown names are dropped and an empty/missing
    # file falls back to the registry default, so single-repo flows just work.
    def target_repos_for(item_id)
      file  = Helpers.item_dir(@ctx, item_id) / "target_repos.json"
      names = Helpers.safe_json_read(file) if file.exist?
      repos = Array(names).filter_map { |n| @ctx.repos[n] }
      repos.empty? ? [@ctx.default_repo] : repos
    end

    # The per-repo base overrides a WP requested, read from
    # <id>/target_base.json ({ "<repo>" => "<base>" }); empty/missing means
    # every repo uses its registry default base.
    def target_bases_for(item_id)
      file = Helpers.item_dir(@ctx, item_id) / "target_base.json"
      (file.exist? ? Helpers.safe_json_read(file) : nil) || {}
    end

    # Persist the repos the LLM chose for a WP (validated against the registry) and
    # update the live state. Names not in the registry are ignored; if none
    # survive, the default repo is used so a fix still ships somewhere. `bases` is
    # a { name => base } map of the per-repo base overrides the LLM declared (via
    # the REPOS `name@base` syntax); it is kept only for valid, chosen repos.
    def set_target_repos(st, names, bases = {})
      repos = Array(names).filter_map { |n| @ctx.repos[n.to_s.strip] }.uniq(&:name)
      repos = [@ctx.default_repo] if repos.empty?
      st.target_repos_file.write(JSON.generate(repos.map(&:name)))
      st.repos = repos

      chosen = repos.map(&:name)
      overrides = (bases || {}).filter_map do |name, base|
        n = name.to_s.strip
        b = base.to_s.strip
        [n, b] if chosen.include?(n) && !b.empty?
      end.to_h
      if overrides.empty?
        safe_rm(st.target_base_file)
      else
        st.target_base_file.write(JSON.generate(overrides))
      end
      st.bases = overrides
    end

    # Rewrite a host path under .opilot/ to its path inside the harness container.
    def container_path(host_path)
      Helpers.state_container_path(@ctx, host_path)
    end

    # Rewrite a host path inside a repo's worktree to its /repos/<name> path
    # inside the harness container.
    def container_path_for(repo, host_path)
      host_path.to_s.sub(repo.worktree_host.to_s, repo.worktree_container)
    end

    # True when a phase will resume an existing per-WP session (so the plan and
    # issue are already in context). False for a fresh session — e.g. the first
    # call, or after the session was cleared — where the prompt must tell the LLM
    # to read the plan instead of assuming it.
    def session_resumable?(st)
      Helpers.file_has_content?(st.session_file)
    end
  end
end
