// Inference gateway — runs in its own container, and is the harness's ONLY
// route to a model.
//
// CONTAINMENT, not authentication, is the load-bearing job here. This was
// once called "authgw", a name that advertised the only OPTIONAL thing it
// does: holding the API key. That is one of four jobs; the other three hold
// whether or not a key exists:
//
//   1. a FIXED upstream, resolved once at boot and never read from the request
//   2. a PINNED address, so the resolved host cannot be swapped under us (DNS
//      rebinding) between the allowlist decision and the connection
//   3. a PATH ALLOWLIST, so a prompt-injected pi can reach inference and
//      nothing else on that upstream
//
// A keyless upstream (a self-hosted OpenAI-compatible server) therefore still
// goes through here. "No secret to hide" is not a reason to bypass it.
//
// pi's models.json points the provider's baseUrl at this gateway and resolves
// its apiKey to OPILOT_GW_TOKEN (a fixed handshake value, not a secret — just
// a sanity gate), so the real key never lives alongside the untrusted
// work-package content the harness container reads.
//
// This gateway converts HEADERS, never PROTOCOLS. It does not read or rewrite
// the request body and stays a streaming forwarder. A different wire protocol
// (anthropic-messages, google-generative-ai) is pi's `api` field in
// models.json, generated by server.js — not this file's concern. The two look
// like the same problem and are not.
const http  = require('http');
const https = require('https');
const dns   = require('dns');

const PORT = 47292;

// pi always talks to this gateway under /v1, whatever the upstream's own
// prefix is. That prefix lives in OPILOT_INFERENCE_URL and is re-applied
// below, so there is exactly one baseUrl on pi's side across every upstream.
const CLIENT_PREFIX = '/v1';

// Everything the harness may reach on the upstream, checked AFTER the /v1
// strip. Ordering matters: strip first, then decide, or a path that is
// allowed once normalised gets refused.
//
// `messages` and `responses` are here because OPILOT_MODEL_API can select
// anthropic-messages or openai-responses; `credits`/`key` are OpenRouter-only
// and serve `./opilot usage`. `models` is a PREFIX rule rather than an exact
// match because google-generative-ai puts the model in the path
// (models/<id>:generateContent).
//
// Everything else is refused — notably Ollama's /api/pull, which takes an
// arbitrary registry host and would otherwise be an exfiltration channel out
// of a container that has no other way out.
const ALLOWED_EXACT = new Set(['chat/completions', 'messages', 'responses', 'credits', 'key']);
const allowedPath = p => ALLOWED_EXACT.has(p) || p === 'models' || p.startsWith('models/');

// RFC 7230 header field-name. Validated because the name comes from config and
// an unchecked value could smuggle CRLF into the outgoing request.
const HEADER_NAME_RE = /^[A-Za-z0-9!#$%&'*+.^_`|~-]+$/;

// Parses the environment into the frozen upstream description every request is
// served from. Exported so tests can exercise it without opening a socket.
// Throws on anything malformed: this runs at boot, and a gateway that starts
// with a half-understood config is worse than one that refuses to start.
function parseConfig(env = process.env) {
  const raw = env.OPILOT_INFERENCE_URL || 'https://openrouter.ai/api/v1';

  let url;
  try {
    url = new URL(raw);
  } catch {
    throw new Error(`OPILOT_INFERENCE_URL is not a URL: ${raw}`);
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') {
    throw new Error(`OPILOT_INFERENCE_URL must be http or https (got ${url.protocol})`);
  }

  // Trailing slash normalised away so the re-applied prefix never doubles a
  // separator: "/api/v1/" + "/chat/completions" would be "/api/v1//chat/...".
  const pathPrefix = url.pathname.replace(/\/+$/, '');

  // Blank is a valid answer, not a missing one: plenty of self-hosted servers
  // want no key at all. Normalised to null so the header is omitted rather
  // than sent empty.
  const apiKey = env.OPILOT_INFERENCE_KEY || null;

  const template = env.OPILOT_INFERENCE_AUTH || 'Authorization: Bearer {key}';
  const colon = template.indexOf(':');
  if (colon < 1) {
    throw new Error(`OPILOT_INFERENCE_AUTH must be "Header-Name: value with {key}" (got: ${template})`);
  }
  const authHeader = template.slice(0, colon).trim().toLowerCase();
  const authValue  = template.slice(colon + 1).trim();
  if (!HEADER_NAME_RE.test(authHeader)) {
    throw new Error(`OPILOT_INFERENCE_AUTH header name is not a valid HTTP token: ${authHeader}`);
  }
  if (!authValue.includes('{key}')) {
    throw new Error(`OPILOT_INFERENCE_AUTH value must contain {key} (got: ${authValue})`);
  }

  const gwToken = env.OPILOT_GW_TOKEN;
  if (!gwToken) throw new Error('OPILOT_GW_TOKEN is not set');

  return Object.freeze({
    https: url.protocol === 'https:',
    host: url.hostname,
    port: url.port ? Number(url.port) : (url.protocol === 'https:' ? 443 : 80),
    pathPrefix,
    apiKey,
    authHeader,
    authValue,
    gwToken,
  });
}

// Maps an inbound request path onto the upstream, or reports why not.
// Returns { path } to forward, or { refuse: <reason> }.
function mapPath(cfg, reqUrl) {
  const q      = reqUrl.indexOf('?');
  const path   = q === -1 ? reqUrl : reqUrl.slice(0, q);
  const query  = q === -1 ? ''     : reqUrl.slice(q);

  if (path !== CLIENT_PREFIX && !path.startsWith(CLIENT_PREFIX + '/')) {
    return { refuse: `path must start with ${CLIENT_PREFIX}` };
  }
  const rest = path.slice(CLIENT_PREFIX.length).replace(/^\/+/, '');

  // Refuse traversal before the allowlist sees it. `models` is a prefix rule,
  // so "models/../../api/pull" would otherwise be ALLOWED here and normalised
  // back to /api/pull by the upstream — the allowlist has to decide on the
  // same string the upstream will act on. Encoded forms are covered too: a
  // literal %2e survives to the upstream, which may decode it.
  if (/(^|\/)\.\.(\/|$)/.test(rest) || /%2e/i.test(rest)) {
    return { refuse: `path traversal is not allowed: ${rest}` };
  }
  if (!allowedPath(rest)) return { refuse: `path not allowed: ${rest}` };

  return { path: `${cfg.pathPrefix}/${rest}${query}` };
}

// Builds the outgoing header set from the inbound one.
//
// The delete is unconditional and is the whole point: today the incoming
// Authorization carries OPILOT_GW_TOKEN, and the old code happened to be safe
// only because it overwrote that same header. The moment the configured header
// is a different name (api-key, for Azure OpenAI) a set-without-delete leaves
// our handshake token in place and ships it to a third party on every call.
function buildHeaders(reqHeaders, cfg) {
  const headers = { ...reqHeaders };
  delete headers['authorization'];
  delete headers[cfg.authHeader];
  if (cfg.apiKey) headers[cfg.authHeader] = cfg.authValue.replace('{key}', cfg.apiKey);
  headers['host'] = cfg.host; // the NAME, not the pinned address
  return headers;
}

// The request handler, separated from createServer so it can be driven
// directly by tests. `deps.request` is the outbound call and `deps.address`
// yields the pinned address.
function createHandler(cfg, deps) {
  const agent = new (cfg.https ? https : http).Agent({ keepAlive: true });

  return function handle(req, res) {
    if (req.method === 'GET' && req.url === '/health') {
      res.writeHead(200); res.end('ok'); return;
    }

    // The client must present the gateway token; reject anything else before
    // we attach the real key. This check is on OUR handshake and is always a
    // Bearer token — it is unrelated to how the upstream wants its own key.
    if (req.headers['authorization'] !== `Bearer ${cfg.gwToken}`) {
      res.writeHead(401, { 'Content-Type': 'text/plain' });
      res.end('unauthorized\n');
      req.resume(); // drain the body so the socket can close cleanly
      return;
    }

    // The runner-only view of what this gateway will actually connect to.
    // Handled before mapPath, whose allowlist is about the UPSTREAM's paths and
    // would refuse this one; behind the token, unlike /health, because it
    // describes the configured upstream.
    //
    // It exists because the runner must not resolve OPILOT_INFERENCE_URL for
    // itself: only this process connects to that host, and only this process
    // knows the address it pinned at boot. `./opilot appsignal` gates on that
    // address being private, and a second lookup elsewhere could answer
    // differently.
    if (req.method === 'GET' && req.url === '/upstream') {
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({
        host: cfg.host, address: deps.address(), port: cfg.port, https: cfg.https,
      }));
      req.resume();
      return;
    }

    const mapped = mapPath(cfg, req.url || '');
    if (mapped.refuse) {
      process.stderr.write(`inference-gw: refused ${req.method} ${req.url} — ${mapped.refuse}\n`);
      res.writeHead(403, { 'Content-Type': 'text/plain' });
      res.end('path not allowed\n');
      req.resume();
      return;
    }

    const upstream = deps.request({
      host: deps.address(),          // pinned address, not the name
      servername: cfg.https ? cfg.host : undefined, // SNI + cert validation
      port: cfg.port,
      method: req.method,
      path: mapped.path,
      headers: buildHeaders(req.headers, cfg),
      agent,
    }, up => {
      res.writeHead(up.statusCode, up.headers);
      up.pipe(res);
    });

    upstream.on('error', err => {
      // A connection-level failure can mean the pinned address went stale —
      // a CDN rotating out the record it handed us at boot. Re-resolve for the
      // NEXT request rather than per request, which would give up the pinning.
      deps.invalidate();
      process.stderr.write(`inference-gw: upstream error: ${err.message}\n`);
      if (!res.headersSent) res.writeHead(502, { 'Content-Type': 'text/plain' });
      res.end('upstream error\n');
    });

    req.pipe(upstream);
  };
}

// Resolves the upstream host to an address once, and again only when a
// connection actually fails. Pinning is what makes the "fixed upstream"
// guarantee real rather than nominal: without it, the host could resolve to
// one address when the allowlist is applied and another when the socket opens.
function createResolver(cfg, lookup = dns.promises.lookup) {
  let current = null;
  const refresh = async () => {
    const { address } = await lookup(cfg.host);
    current = address;
    return address;
  };
  return {
    refresh,
    address: () => current,
    invalidate: () => { current = null; },
    // Re-resolve lazily when a previous request invalidated the address.
    ensure: async () => (current ? current : refresh()),
  };
}

async function startServer() {
  const cfg = parseConfig();
  const resolver = createResolver(cfg);
  await resolver.refresh();

  const handler = createHandler(cfg, {
    request: (options, cb) => (cfg.https ? https : http).request(options, cb),
    address: () => resolver.address(),
    invalidate: () => resolver.invalidate(),
  });

  const server = http.createServer((req, res) => {
    // Restore a pinned address dropped by an earlier failure before serving.
    resolver.ensure().then(() => handler(req, res)).catch(err => {
      process.stderr.write(`inference-gw: could not resolve ${cfg.host}: ${err.message}\n`);
      if (!res.headersSent) res.writeHead(502, { 'Content-Type': 'text/plain' });
      res.end('upstream unresolvable\n');
    });
  });

  server.listen(PORT, '0.0.0.0', () => {
    const scheme = cfg.https ? 'https' : 'http';
    // "Which upstream is this run using" has to be answerable from the log
    // alone — it is now configurable, so it can no longer be assumed.
    process.stderr.write(
      `inference-gw listening on ${PORT} → ${scheme}://${cfg.host}:${cfg.port}${cfg.pathPrefix} ` +
      `(pinned ${resolver.address()}, auth ${cfg.apiKey ? `${cfg.authHeader} header` : 'none'})\n`
    );
  });
  return server;
}

if (require.main === module) {
  startServer().catch(err => {
    process.stderr.write(`inference-gw: ${err.message}\n`);
    process.exit(1);
  });
}

module.exports = { parseConfig, mapPath, buildHeaders, createHandler, createResolver, startServer };
