require "json"
require "tempfile"
require "time"
require "uri"
# Ruby 4.0 dropped the full CGI library; cgi/escape is the part that survived,
# and CGI.escapeHTML is all .mention needs.
require "cgi/escape"
require "rainbow"
require "tty-markdown"

module OPilot
  module Helpers
    # File/JSON idioms shared across classes that don't all `include Helpers`
    # (Pull, UI), so they're module functions like .wp_label below.

    # Per-WP state lives under .opilot/work_packages/<op_host>/<id>/ —
    # namespaced by the OpenProject instance (see Context#op_host) so different
    # instances don't collide. One source of truth for that path, used
    # everywhere instead of re-joining the literal.
    def self.items_dir(ctx)
      ctx.state_dir / "work_packages" / ctx.op_host
    end

    def self.item_dir(ctx, id)
      items_dir(ctx) / id.to_s
    end

    # Rewrite a host path under .opilot/ to its path inside the harness
    # container, where .opilot is mounted read-only at /state. A module function
    # as well as an instance method (#container_path) because Pull writes
    # container paths into item.json and does not include Helpers.
    def self.state_container_path(ctx, host_path)
      host_path.to_s.sub(ctx.state_dir.to_s, ctx.state_container)
    end

    # The <id>/repos/<name>/ dirs under one work-package dir that hold a shipped
    # PR. One definition, because "what counts as a shipped PR dir" is asked both
    # of every work package (the gh-agent scan) and of one (`dev refresh`).
    def self.pr_dirs_in(item_dir)
      repos_dir = item_dir / "repos"
      return [] unless repos_dir.exist?
      repos_dir.children.select(&:directory?).sort
               .select { |d| file_has_content?(d / "pr_url.txt") }
    end

    # The same shape for the `pd` pipeline's per-change state, in its own
    # namespace (changes/ vs work_packages/) since a change id and a work-package
    # id are different things that could otherwise collide.
    def self.changes_dir(ctx)
      ctx.state_dir / "changes" / ctx.op_host
    end

    def self.change_dir(ctx, change_id)
      changes_dir(ctx) / change_id.to_s
    end

    # One "Usage:" shape for every command, so a bad invocation reads the same
    # whichever one it was. A module function because CLI does not include
    # Helpers, and it was the second verbatim copy that proved the point.
    def self.usage!(name, arg_spec, example = nil)
      $stderr.puts "Usage: ./opilot #{name} #{arg_spec}#{example ? "   (#{example})" : ""}"
      raise OPilot::FatalError
    end

    # `./opilot appsignal`'s per-incident state. Namespaced by OpenProject host
    # for the reason items_dir is: wp_id.txt records a work package on ONE
    # instance, and incident #4711 means nothing on another. The app segment is
    # there because an incident number is only unique within one app.
    def self.incident_dir(ctx, app, number)
      ctx.state_dir / "appsignal" / ctx.op_host / slugify(app, fallback: "app") / number.to_s
    end

    # Filesystem-safe slug of a title. One implementation, because the rule (what
    # "&" becomes, what counts as a separator, hyphen trimming) has to be identical
    # everywhere: an attachment's directory name and the markdown link pointing at
    # it are generated by separate call sites, and a slug that differs by one
    # character between them silently produces a broken link.
    def self.slugify(str, fallback: "item", limit: 60)
      s = str.to_s.downcase.gsub("&", "and").gsub(/[^a-z0-9]+/, "-").gsub(/\A-+|-+\z/, "")
      s.empty? ? fallback : s[0, limit]
    end

    # A file exists and is non-empty — the "has real content" check used for
    # plans, PR descriptions, session ids, and shipped markers.
    def self.file_has_content?(path)
      path.exist? && path.size > 0
    end

    # Parse a JSON file, returning nil on any read/parse error. Callers add
    # their own `|| {}` / `|| []` fallback where they depend on one.
    def self.safe_json_read(path)
      JSON.parse(path.read)
    rescue StandardError
      nil
    end

    # An OpenProject mention of a user, so a comment notifies and addresses them
    # by name. Falls back to the bare name, then to "", when the details are
    # missing. Display names are free text an attacker can influence, so the name
    # is HTML-escaped and the id must be numeric.
    def self.mention(name, user_href)
      escaped = CGI.escapeHTML(name.to_s)
      id      = user_href.to_s.split("/").last.to_s
      return escaped unless id.match?(/\A\d+\z/)
      %Q(<mention class="mention" data-id="#{id}" data-type="user" data-text="#{escaped}">@#{escaped}</mention>)
    end

    # ── implementation options ──────────────────────────────────────────────
    #
    # A plan call may answer with implementation options instead of a plan (see
    # Prompts::OPTIONS_CONTRACT). Both readers of that answer live here — the
    # agent, which offers the options in a work-package comment, and the terminal
    # runner, which offers them at the console — so the parsing and the wording of
    # a chosen option are written once.

    # One pipe-delimited option line's fields, or nil when the line doesn't
    # match — shared by parse_options and parse_leading_options below.
    def self.parse_option_line(line)
      fields = line.to_s.split("|").map(&:strip)
      return nil unless fields.length >= 3
      number = fields[0][/\d+/]
      return nil unless number
      { "n" => number.to_i, "title" => fields[1], "summary" => fields[2],
        "repos" => fields[3].to_s.split(",").map(&:strip).reject(&:empty?),
        "size" => fields[4].to_s }
    end

    # Read the OPTIONS block: one pipe-delimited line per option. Lines that do
    # not parse are dropped, so a stray sentence around the block costs nothing,
    # and a duplicate number keeps its first line — the numbers are what a reader
    # answers with. Used for the stops-after-options answer, where nothing but
    # option lines is expected anywhere in the body.
    def self.parse_options(body)
      body.to_s.lines.filter_map { |line| parse_option_line(line) }
        .uniq { |o| o["n"] }.sort_by { |o| o["n"] }
    end

    # Whether `text` answers with OPTIONS (Prompts::OPTIONS_CONTRACT) — tolerant
    # of a preamble sentence before the sentinel line, the same accommodation
    # #record_chosen_repos' REPOS: match already makes and the NEEDS_INFO check
    # below makes too: a local model in particular often reasons in prose before
    # it reaches the actual marker ("I have enough from the issue... OPTIONS").
    # Requires the sentinel ALONE on its own line, so an ordinary sentence that
    # happens to use the word "options" is never mistaken for the block.
    def self.options_sentinel?(text)
      text.to_s.lines.any? { |l| l.strip == Prompts::OPTIONS_SENTINEL }
    end

    # Split a writer's answer into its OPTIONS line(s) and whatever follows
    # (Prompts::OPTIONS_CONTRACT: name the approach, then — when there's only
    # one — continue straight into the plan in the same response). The
    # sentinel is found anywhere, per #options_sentinel? above, and everything
    # before and including it is dropped along with it — a preamble sentence
    # is not part of the contract's answer, the same as a NEEDS_INFO preamble
    # is dropped where it is read. From there, only CONTIGUOUS option lines are
    # consumed: a plan can itself contain pipe-delimited markdown table rows,
    # which a tolerant scan like parse_options' would misread as more options.
    def self.parse_leading_options(body)
      lines = body.to_s.lines
      start = lines.index { |l| l.strip == Prompts::OPTIONS_SENTINEL }
      return [[], body.to_s.lstrip] unless start
      lines = lines[(start + 1)..] || []
      options = []
      while (parsed = parse_option_line(lines.first))
        options << parsed
        lines.shift
      end
      [options.uniq { |o| o["n"] }.sort_by { |o| o["n"] }, lines.join.lstrip]
    end

    WP_BEGIN     = /\A[ \t]*BEGIN WORK PACKAGE[ \t]*\z/
    WP_END       = /\A[ \t]*END WORK PACKAGE[ \t]*\z/
    SUBJECT_LINE = /\ASUBJECT:[ \t]*(.+)\z/i
    TYPE_LINE    = /\ATYPE:[ \t]*(.+)\z/i
    LINK_LINE    = /\ALINK:[ \t]*(.+)\z/i
    FENCE_LINE   = /\A[ \t]*(`{3,}|~{3,})/

    # How a new work package hangs off the one that asked for it. "child" is the
    # only value that makes it one; everything else, including a missing LINK
    # line, is a peer. The default is deliberately the conservative direction:
    # OpenProject derives a parent's dates and progress from its children, so a
    # child link CHANGES the source work package, while a relation does not.
    WP_LINKS        = %w[child related].freeze
    DEFAULT_WP_LINK = "related".freeze

    # Read the work packages a `create wp` answer asks for (Prompts.create_wp).
    # Each one is a block — BEGIN WORK PACKAGE, a SUBJECT: line, an optional
    # TYPE: and LINK: line, the description, END WORK PACKAGE — and a request
    # that names several pieces of work answers with several blocks, in order.
    #
    # Returns [] when the answer holds no usable block, which the caller treats
    # as unusable: one bounded retry, then it gives up. That is safe precisely
    # because nothing is created yet, and it must stay strict, because a work
    # package cannot be deleted and so a block opilot half-understands must
    # never reach the POST.
    #
    # Three rules do the work:
    #
    # - BOTH marker lines are required, each alone on its line. An unclosed
    #   block means the answer was CUT OFF — all N blocks share one output
    #   budget, so a truncated last block is the real failure mode here, and
    #   without the end marker it would be created as a work package with half a
    #   description. One unclosed block rejects the whole answer.
    # - Marker lines inside a fenced code block are text. A description quotes
    #   the thread, so it can contain anything — including a comment somebody
    #   pasted opilot's own answer into. PD::TasksFile learned the same lesson
    #   with an example `##` heading.
    # - Text between blocks is ignored. Narration between blocks is harmless;
    #   only what sits INSIDE one becomes a work package.
    def self.parse_work_packages(body)
      blocks = []
      open   = nil
      fence  = nil
      body.to_s.lines.each do |raw|
        line  = raw.chomp
        fence = fence_state(fence, line)
        # Inside a fence: description text, whatever it says.
        next open&.<<(line) unless fence.nil?

        if line.match?(WP_BEGIN)
          # A second BEGIN with no END between: the first block is unterminated,
          # which is the same broken answer as a truncated one.
          return [] if open
          open = []
        elsif line.match?(WP_END)
          return [] unless open
          blocks << open
          open = nil
        else
          open&.<<(line)
        end
      end
      return [] if open   # cut off mid-block
      blocks.filter_map { |block| work_package_fields(block) }
    end

    # Whether this line leaves us inside a fenced code block, and in which
    # fence. Nil means outside.
    def self.fence_state(fence, line)
      marker = line[FENCE_LINE, 1] or return fence
      return marker[0] if fence.nil?
      marker.start_with?(fence) ? nil : fence
    end
    private_class_method :fence_state

    # One block's fields. Only the LEADING lines are read as fields, so a
    # description that discusses a "SUBJECT:" line of its own cannot move the
    # subject. A block with no subject is dropped rather than guessed at.
    #
    # SUBJECT, TYPE and LINK are one header and are read in ANY order: a writer
    # that swaps two of them has still said everything, and rejecting it costs a
    # whole retry call (a local model swapped SUBJECT and TYPE on a real
    # `appsignal fix` run). TYPE and LINK stay optional.
    def self.work_package_fields(lines)
      lines  = lines.drop_while { |l| l.strip.empty? }
      fields = {}
      loop do
        line = lines.first.to_s
        if (subject = line[SUBJECT_LINE, 1])
          fields["subject"] ||= subject.strip
        elsif (type = line[TYPE_LINE, 1])
          fields["type"] ||= type.strip
        elsif (link = line[LINK_LINE, 1])
          fields["link"] ||= link.strip
        else
          break
        end
        lines = lines.drop(1)
      end
      return nil if fields["subject"].to_s.empty?

      link = fields["link"].to_s.downcase
      { "subject"     => fields["subject"],
        "type"        => fields["type"].to_s,
        "link"        => WP_LINKS.include?(link) ? link : DEFAULT_WP_LINK,
        "description" => lines.join("\n").strip }
    end
    private_class_method :work_package_fields

    ARTIFACT_BEGIN         = /\A[ \t]*BEGIN ARTIFACT[ \t]*\z/
    ARTIFACT_END           = /\A[ \t]*END ARTIFACT[ \t]*\z/
    ARTIFACT_FILENAME_LINE = /\AFILENAME:[ \t]*(.+)\z/i
    ARTIFACT_TITLE_LINE    = /\ATITLE:[ \t]*(.+)\z/i

    # Read the artifacts a chat answer carries (Prompts.artifact_block), and
    # return [artifacts, remainder] — the remainder being the answer with every
    # block removed, which is what gets posted as the comment.
    #
    # The block shape mirrors .parse_work_packages, but the failure rule is the
    # OPPOSITE and deliberately so: there, one bad block rejects the whole answer,
    # because a work package can never be deleted. Here a malformed or truncated
    # block drops only ITSELF and the reply is still posted — an unreadable
    # diagram is no reason to swallow the answer that came with it.
    #
    # As there: marker lines inside a fence are text (a report quotes things, and
    # somebody will paste opilot's own answer into a comment), and a ```mermaid
    # fence inside a block therefore cannot end it.
    def self.parse_artifacts(body)
      artifacts = []
      kept      = []   # lines outside every block, joined verbatim
      open      = nil
      fence     = nil
      body.to_s.lines.each do |raw|
        line  = raw.chomp
        fence = fence_state(fence, line)
        # Inside a fence: content, whatever it says.
        unless fence.nil?
          open ? open << line : kept << raw
          next
        end

        if line.match?(ARTIFACT_BEGIN)
          open = []   # a second BEGIN abandons an unterminated block
        elsif line.match?(ARTIFACT_END)
          artifacts << open if open
          open = nil
        else
          open ? open << line : kept << raw
        end
      end
      # `open` here was cut off mid-block: drop it, but keep everything before it.
      [artifacts.filter_map { |block| artifact_fields(block) }, kept.join]
    end

    # One block's fields. Only the LEADING lines are read as a header, so a report
    # that discusses a `TITLE:` line of its own cannot move the title. A block with
    # no filename, or no content, is dropped rather than guessed at.
    def self.artifact_fields(lines)
      lines  = lines.drop_while { |l| l.strip.empty? }
      fields = {}
      loop do
        line = lines.first.to_s
        if (name = line[ARTIFACT_FILENAME_LINE, 1])
          fields["filename"] ||= name.strip
        elsif (title = line[ARTIFACT_TITLE_LINE, 1])
          fields["title"] ||= title.strip
        else
          break
        end
        lines = lines.drop(1)
      end
      return nil if fields["filename"].to_s.empty?

      content = lines.join("\n").strip
      return nil if content.empty?
      { "filename" => fields["filename"], "title" => fields["title"].to_s, "content" => content }
    end
    private_class_method :artifact_fields

    # A filesystem- and gist-safe name for an artifact, always `.md` (a gist
    # serves raw content as text/plain, so markdown with a ```mermaid fence is the
    # one format that renders). De-duplicated against `taken`, which is
    # load-bearing: a gist's files are keyed by name, so two blocks slugging to
    # the same name would silently collapse into one.
    def self.artifact_filename(raw, taken: [])
      stem = slugify(File.basename(raw.to_s.strip).sub(/\.[^.]+\z/, ""), fallback: "artifact")
      name = "#{stem}.md"
      n    = 1
      while taken.include?(name)
        n += 1
        name = "#{stem}-#{n}.md"
      end
      name
    end

    # A project's work-package types as [{ "id", "name" }], from a
    # Clients::OpenProject#project_types response.
    def self.type_list(body)
      ((body || {}).dig("_embedded", "elements") || [])
        .map { |t| { "id" => t["id"], "name" => t["name"].to_s } }
    end

    # The type with this name, case-insensitively — instances style these names
    # inconsistently ("Feature", "FEATURE"), so an exact match would be pure
    # friction. One definition, because `pd init`, `@opilot create wp` and
    # `./opilot op wp create` all resolve a type the operator or the writer named,
    # and a name that resolves in one must resolve in all three.
    def self.find_type(types, name)
      return nil if name.to_s.strip.empty?
      types.to_a.find { |t| t["name"].to_s.casecmp?(name.to_s) }
    end

    # Whether this token may create work packages in `project_json` (a project
    # resource body). OpenProject renders these links only for a user who holds
    # :add_work_packages, so their absence is a real answer rather than a guess —
    # and a preflight beats a 403 raised after an LLM call has already run.
    #
    # It lives here, not in PD::ResolvedIds where it started, because agent.rb
    # needs it too and nothing under pd/ may be required at boot.
    CREATE_WP_LINKS = %w[createWorkPackageImmediately createWorkPackage].freeze

    def self.create_wp_allowed?(project_json)
      links = (project_json || {})["_links"] || {}
      CREATE_WP_LINKS.any? { |name| links.key?(name) }
    end

    # The TYPE line's menu. An empty registry is stated rather than left blank, so
    # the writer omits the line instead of inventing a type name. One definition,
    # because every prompt carrying a `TYPE:` line reads the same list.
    def self.types_for_prompt(types)
      names = types.to_a.map { |t| t["name"].to_s }.reject(&:empty?)
      names.empty? ? "(unknown — leave the TYPE line out)" : names.join(", ")
    end

    # The v3 create body. `_links.type` is present only when a type was resolved:
    # with no type at all OpenProject assigns the project's first enabled type.
    #
    # One definition, because the subject truncation and the markdown description
    # shape have to hold at every site that creates a work package.
    def self.wp_payload(project:, type:, subject:, description:)
      links = { "project" => { "href" => "/api/v3/projects/#{project}" } }
      links["type"] = { "href" => "/api/v3/types/#{type["id"]}" } if type

      { "subject"     => subject.to_s[0, 200],
        "description" => { "format" => "markdown", "raw" => description.to_s },
        "_links"      => links }
    end

    # The create form's three-way answer, in one place: nil when the form did not
    # answer about the payload at all (403, an HTML error from a proxy) or found
    # nothing wrong, else the validation errors.
    #
    # The form answers **200 even for a payload it rejects**, which is why
    # `_embedded.validationErrors` decides and the status code does not — a quirk
    # subtle enough that Clients::OpenProject#create_work_package_form documents
    # it, and one that must not be encoded twice.
    def self.form_validation_errors(code, form)
      return nil unless code == 200 && form.is_a?(Hash)
      errors = form.dig("_embedded", "validationErrors")
      errors.is_a?(Hash) && !errors.empty? ? errors : nil
    end

    # Which part of the BEGIN/END WORK PACKAGE contract the last answer missed,
    # said back to the writer on the one retry. Read off the answer itself rather
    # than from the parser, whose answer is only "nothing usable" — the three
    # misses below need three different corrections.
    #
    # It lives beside WP_BEGIN/WP_END and .parse_work_packages on purpose: the
    # markers, the parser and this correction text are ONE contract, and a copy
    # per caller is how one of them starts teaching the old format. `many` is the
    # only thing that varies between callers.
    def self.wp_format_miss(answer, many: false)
      # WP_BEGIN/WP_END anchor a whole LINE, so they are matched line by line.
      lines = answer.to_s.lines.map(&:chomp)
      if lines.none? { |l| l.match?(WP_BEGIN) }
        "Your last answer had no `BEGIN WORK PACKAGE` line. #{many ? "Every work package needs" : "It needs"} " \
          "one, alone on its own line, and a closing `END WORK PACKAGE` line."
      elsif lines.none? { |l| l.match?(WP_END) }
        "Your last answer opened a block and never closed it. Write the closing " \
          "`END WORK PACKAGE` line#{many ? " for every block" : ""}, alone on its own line."
      else
        "Your last answer's #{many ? "blocks were" : "block was"} unreadable — #{many ? "each one" : "it"} " \
          "needs a `SUBJECT: <one line>` line in the header, above the description."
      end
    end

    # Resolve a reader's answer to the plan-call focus for the option they chose,
    # or nil when the answer names no option (it is then plain direction). A
    # **leading** number selects: "2", "option 2" and "2 but keep the toast" all
    # choose option 2, and whatever follows the number rides along instead of
    # being lost. One implementation, because a work-package comment and the
    # terminal prompt must read an answer the same way.
    def self.option_choice(options, text)
      number, extra = text.to_s.strip.match(/\A(?:option\s+)?(\d{1,2})\b[\s,.:;–—-]*(.*)\z/im)&.captures
      return nil unless number
      option = options.to_a.find { |o| o["n"] == number.to_i }
      return nil unless option
      option_focus_text(option, extra.to_s)
    end

    # The plan-call focus for a chosen option. `extra` is anything the reader
    # wrote after the number ("2 but keep the toast"), which is direction on top
    # of the option and must not be dropped. The option's own repo list is passed
    # on as the expected targets, so the repos named in the offer and the repos in
    # the plan's REPOS line do not drift apart.
    def self.option_focus_text(option, extra = "")
      repos = option["repos"].to_a.join(", ")
      text  = +"The reporter chose option #{option["n"]} of the options you offered: " \
               "#{option["title"]} — #{option["summary"]} " \
               "Plan that option only, and do not plan the other options."
      text << " The offer named these repos for it: #{repos}. Keep to them in the REPOS line " \
              "unless the code makes that impossible; if you must change them, say why in the plan." unless repos.empty?
      text << " The reporter added: #{extra.strip}" unless extra.to_s.strip.empty?
      text
    end

    # Write JSON to `path` atomically (tempfile in the same dir, then rename),
    # so a crash mid-write never leaves a half-written cache. `name` is the
    # tempfile prefix. `pretty:` is for the files a human reads in a diff (the
    # `pd` pipeline commits tracker.json into the spec store) — they need the
    # same crash-safety as the machine-only caches, just not on one line.
    def self.write_json_atomic(path, data, name, pretty: false)
      tmp = Tempfile.new(name, path.dirname)
      tmp.write(pretty ? JSON.pretty_generate(data) : JSON.generate(data))
      tmp.close
      File.rename(tmp.path, path.to_s)
    rescue StandardError
      tmp&.unlink
      raise
    end

    # Set the process git identity (author + committer) to the GitHub account
    # the given token belongs to, so a PR's commits are attributed to the
    # identity that publishes it and the operator's private email never lands
    # on a public PR. Runs once per process; a no-op when no token is given
    # (planning-only). Falls back silently to the host identity ./opilot
    # exported if the lookup fails.
    def self.adopt_github_author!(token)
      return if @github_author_adopted
      return unless token
      name, email = Clients::GitHub.new(token).author_identity
      ENV["GIT_AUTHOR_NAME"]  = ENV["GIT_COMMITTER_NAME"]  = name
      ENV["GIT_AUTHOR_EMAIL"] = ENV["GIT_COMMITTER_EMAIL"] = email
      @github_author_adopted = true
    rescue StandardError => e
      warn "  Warning: couldn't resolve the publishing git identity (#{e.message}); using host git identity"
    end

    # Turn a "how far back" answer into an ISO8601 cutoff. Accepts a relative
    # span ("1h", "2 days", "1 week", "1 month", "1 year"), an absolute time, or
    # blank/"now" (= now). Months and years use 30- and 365-day approximations,
    # which is plenty for a scan floor. Shared by the OpenProject agent (Pull)
    # and the GitHub agent (GhPull) so the "scan from" prompt parses identically.
    def self.parse_scan_from(input)
      input = input.to_s.strip.downcase
      return Time.now.utc.iso8601 if input.empty? || input == "now"
      if (m = input.match(/\A(\d+)\s*([a-z]+)\z/))
        n = m[1].to_i
        # Classify on the whole unit, not the first letter: "m" is minutes but
        # "mo"/"month" is months, so a first-char test can't tell them apart.
        seconds = case m[2]
                  when "m", /\Amin(ute)?s?\z/   then n * 60
                  when /\Ah(our)?s?\z/           then n * 3600
                  when /\Ad(ay)?s?\z/            then n * 86400
                  when /\Aw(eek)?s?\z/           then n * 604800
                  when /\Amo(n(th)?)?s?\z/       then n * 2592000
                  when /\Ay(ear)?s?\z/           then n * 31536000
                  end
        return (Time.now - seconds).utc.iso8601 if seconds
      end
      begin
        Time.parse(input).utc.iso8601
      rescue ArgumentError
        puts "  Could not parse '#{input}' — defaulting to now"
        Time.now.utc.iso8601
      end
    end

    # Per-WP working state: the shared paths under work_packages/<host>/<id>/ plus
    # the branch and the chosen target repos. PR-scoped artifacts (pr.md,
    # pr_url.txt, gh caches) live under <id>/repos/<name>/ since a WP may ship to
    # several repos — resolve them with the per-repo helpers below. Shared by both
    # runners (agent and the terminal fix/plan flow) via #state_for.
    ItemState = Struct.new(:item_id, :subject, :branch, :repos, :bases, :item_dir, :plan_file,
                           :item_file, :related_file, :target_repos_file,
                           :target_base_file, :options_file, :created_wps_file,
                           :session_file, keyword_init: true) do
      # Per-repo artifact directory (<id>/repos/<name>/), created on demand.
      def repo_dir(repo)
        dir = item_dir / "repos" / repo_name(repo)
        dir.mkpath
        dir
      end

      def pr_desc_file(repo); repo_dir(repo) / "pr.md"; end
      def pr_url_file(repo);  repo_dir(repo) / "pr_url.txt"; end

      # The plan gist URL, cached per-WP (not per-repo): plan.md is shared across
      # every repo a WP ships to, so all their PRs link the same gist.
      def gist_url_file; item_dir / "gist_url.txt"; end

      # Where one chat answer's artifacts are mirrored, keyed by the comment that
      # asked for them so two answers cannot overwrite each other.
      def artifact_dir(comment_at)
        dir = item_dir / "artifacts" / Helpers.slugify(comment_at, fallback: "chat")
        dir.mkpath
        dir
      end

      # The base branch this WP's PR targets in `repo`: the per-WP override the
      # user requested (target_base.json), else the repo's registry default. The
      # fix branch is both created from and the PR opened against this branch.
      def base_for(repo)
        (bases || {})[repo_name(repo)] || repo.base
      end

      private

      def repo_name(repo)
        repo.respond_to?(:name) ? repo.name : repo.to_s
      end
    end

    # A markdown link to an OpenProject document, for text that will be rendered
    # by GitHub. Always a link, never a bare "#118": GitHub autolinks that to
    # issue/PR 118 in whatever repo the text lands in, so a document reference
    # silently turns into a pointer at an unrelated pull request. Inside link
    # text the autolinker leaves it alone, and the reader gets the real document.
    def self.document_link(ctx, id, title = nil)
      label = title.to_s.empty? ? "Document ##{id}" : "##{id} #{title}"
      "[#{label}](#{ctx.op_url}/documents/#{id})"
    end

    # The user-facing id of a work-package resource: semantic ("PROJ-123") when
    # the instance runs in semantic mode, numeric otherwise. The API accepts
    # either form in work-package routes, so this is the only id opilot keeps.
    # Falls back to "id" for instances that predate the displayId field.
    #
    # One definition, because the poll cache and every link opilot publishes must
    # name a work package the same way.
    def self.display_id(wp)
      id = (wp || {})["displayId"]
      (id.nil? || id.to_s.empty? ? (wp || {})["id"] : id).to_s
    end

    # The browser URL of a work package on this instance.
    def self.wp_url(ctx, id)
      "#{ctx.op_url}/work_packages/#{id}"
    end

    # A work package id as the user types it: numeric ("59942") or semantic
    # ("PROJ-123", instances in semantic-identifier mode). Mirrors OpenProject's
    # WorkPackage::SemanticIdentifier::ID_ROUTE_CONSTRAINT.
    WP_ID_PATTERN = /\A(?:\d+|[A-Z][A-Z0-9_]*-\d+)\z/

    # Single source of truth for log-line timestamps — both the time format and
    # the bracket wrapping — so every line opilot writes shares one format.
    LOG_TIME_FORMAT = "%H:%M:%S"

    # Render Markdown as ANSI for the terminal — used both for the LLM's streamed
    # text and for re-displaying saved plans from disk, so they look the same.
    # Skipped when stdout isn't a tty (piped, captured by tests, redirected);
    # then the raw, cyan-tinted text is shown. Falls back to the raw text if
    # rendering raises (e.g. a partial fence).
    def render_markdown(text)
      return Rainbow(text).cyan unless $stdout.tty?
      TTY::Markdown.parse(text)
    rescue StandardError
      Rainbow(text).cyan
    end

    def log_timestamp
      Time.now.strftime(LOG_TIME_FORMAT)
    end

    # Everything after the LAST `<MARKER>:` line, or the whole text when the
    # marker is absent.
    #
    # This is the shape every "the answer is the marked part" contract uses, and
    # the reason is always the same: a model under pressure narrates before it
    # answers, however firmly a prompt says not to. A LEADING sentinel fights that
    # instinct — and loses expensively, since a model can spend its whole output
    # budget getting ready to comply and stop with `length`, having produced
    # nothing. A trailing marker turns the same narration into discarded scratch.
    def self.after_marker(text, marker)
      text.to_s.split(/^#{Regexp.escape(marker)}:[ \t]*$/, -1).last.to_s.strip
    end

    # The PR-reply prompts (Prompts::REPLY_CONTRACT) mark the comment to post
    # with a final "REPLY:" line; anything the model produced before it —
    # narration about tooling trouble, "here's my reply:" framing — is discarded
    # rather than posted. Output without the marker is posted whole, and the
    # last marker wins if the text contains several.
    #
    # The marker may carry the reply on its own line here, so this one does not
    # anchor the line end the way .after_marker does.
    def self.extract_reply(text)
      text.to_s.split(/^REPLY:[ \t]*/, -1).last.to_s.strip
    end

    def log_prefix
      "[ #{log_timestamp} ]"
    end

    def log_script(msg)
      prefix = log_prefix
      msg.each_line do |line|
        formatted = Rainbow("#{prefix} #{line.chomp}").bold
        @ctx.log_file.open("a") { |f| f.puts(formatted) }
        $stdout.puts(formatted)
      end
      $stdout.print(Rainbow("").gray) # set gray for subsequent docker output
      $stdout.flush
    end

    def strip_ansi(str)
      Rainbow.uncolor(str)
    end

    # Run one polling pass, surviving any uncaught failure. A long-running agent
    # must not die because a single poll hit a dropped connection or a flaky API
    # response — log it and let the loop retry on the next tick. The client-level
    # retries (Clients::HTTP / Clients::GitHub) handle the common transient
    # cases; this is the backstop for anything that still escapes. Ctrl-C is
    # unaffected: it exits via SystemExit, which is not a StandardError.
    def guarded_tick(label = "Poll")
      yield
    rescue => e
      log_script "#{label} failed (#{e.class}: #{e.message}) — retrying next tick"
    end

    # Inline label for a work package id, mirroring OpenProject's
    # WorkPackage::SemanticIdentifier.format_display_id: semantic ids are
    # self-describing ("PROJ-42"); classic numeric ids keep the "#42" prefix.
    def self.wp_label(id)
      id.to_s.match?(/[A-Za-z]/) ? id.to_s : "##{id}"
    end

    def wp_label(id)
      Helpers.wp_label(id)
    end

    # Shared by the commit subject and the PR title so the two stay identical.
    def self.pr_title(id, subject)
      "[#{wp_label(id)}] #{subject}"
    end

    def pr_title(id, subject)
      Helpers.pr_title(id, subject)
    end

    # Calls the user back for an input prompt that typically follows a long
    # unattended the LLM run. OSC 9 posts a desktop notification in terminals
    # that support it (Ghostty, iTerm2, WezTerm, kitty); others drop the
    # sequence. The BEL after it rings the bell everywhere else (sound, dock
    # bounce, tab highlight — whatever the emulator is configured to do).
    def ping_terminal(message = "opilot is waiting for your input")
      $stdout.print("\e]9;#{message}\e\\\a")
      $stdout.flush
    end

    # One terminal choice prompt, shared by every [y]/[s]/[d]-style question.
    #
    # `choices` is { result => [accepted answers…] }, the FIRST answer of each
    # being its letter. The re-ask hint is built from those letters, so it cannot
    # drift from what the prompt accepts. `default:` is what an empty line means,
    # for the prompts that have an obvious yes.
    #
    # Prompts that accept free text (FixRunner#prompt_option_choice) or that ask
    # once without re-asking (UI#reset) are deliberately not routed through here.
    def prompt_choice(label, choices, default: nil)
      table   = {}
      choices.each { |result, answers| Array(answers).each { |a| table[a] = result } }
      letters = choices.values.map { |answers| Array(answers).first }
      hint    = letters.length > 1 ? "#{letters[0..-2].join(", ")}, or #{letters.last}" : letters.first.to_s
      loop do
        print "  #{label}: "
        answer = $stdin.gets&.chomp&.downcase || ""
        return default if answer.empty? && default
        result = table[answer]
        return result if result
        puts "  Please enter #{hint}."
      end
    end

    # The one push-safety rule: no push ever lands on a canonical repo (a
    # registry upstream). opilot publishes only from the contributor bot's own
    # fork, so a canonical target is always a mistake — the head of a PR a
    # maintainer adopted, or a fork lookup that resolved to the upstream itself
    # — and is refused outright rather than prompted for. Pushes anywhere else
    # (the bot's fork) pass straight through. Returns true when the push must
    # NOT happen, so callers read `return if refuse_canonical_push?(…)`.
    def refuse_canonical_push?(target_repo, branch)
      return false unless canonical_repo?(target_repo)
      log_script "Refusing to push #{branch} to #{target_repo} — opilot only pushes to the " \
                 "contributor bot's fork; a canonical repo is a maintainer's to write to."
      true
    end

    # Is this "owner/repo" one of the registry upstreams, i.e. a canonical repo?
    # (Registry#by_upstream can't answer this — it falls back to the default repo.)
    def canonical_repo?(owner_repo)
      @ctx.repos.all.any? { |r| r.upstream.casecmp?(owner_repo.to_s) }
    end

    # The OpenProject instance host (no port), for matching WP links, or nil.
    def op_link_host
      URI(@ctx.op_url.to_s).host
    rescue URI::InvalidURIError
      nil
    end

    # Demote every ATX markdown heading to bold, for anything posted to a work
    # package: the activity tab is a narrow column, so a plan with five `##`
    # sections spends most of its width on its own titles. Bold reads the same and
    # costs one line. Applied centrally in `#add_comment` rather than per caller,
    # since the text comes from the LLM as often as from opilot and prompt guidance
    # alone doesn't hold.
    #
    # Fenced blocks are left alone (a leading `#` there is a code comment or a
    # shell prompt), and so are setext headings — `---` is usually a rule.
    def self.demote_headings(text)
      fenced = false
      text.to_s.lines.map do |line|
        body    = line.chomp
        newline = line.end_with?("\n") ? "\n" : ""
        fenced = !fenced if body.lstrip.start_with?("```", "~~~")
        next line if fenced
        # A hash run with no text after it is still a heading (an empty one);
        # `#tag` with no space is not.
        m = body.match(/\A {0,3}\#{1,6}(?:[ \t]+(.*))?\z/)
        next line unless m
        title = m[1].to_s.sub(/[ \t]*#+[ \t]*\z/, "").strip   # drop an optional closing run
        (title.empty? ? "" : "**#{title}**") + newline
      end.join
    end

    # Defang every OpenProject WP link (http→hxxp). The link is there so a PR can
    # be traced back to its WP and later adopted, but OpenProject's GitHub
    # integration also scans PR bodies for it and would auto-reference the WP,
    # cluttering its activity tab with a fork PR nobody has taken over. `hxxp://`
    # fails the integration's `https?://…/(?:work_packages|wp)/<id>` matcher while
    # leaving the id readable; `op_ticket_id` reads it back and `opilot-adopt` re-fangs
    # it. Host-scoped, idempotent, and a no-op when the host is unknown.
    def neutralize_wp_links(text)
      host = op_link_host
      return text if host.to_s.empty?
      text.to_s.gsub(
        %r{http(s?://#{Regexp.escape(host)}(?::\d+)?/(?:\S+?/)*?(?:work_packages|wp)/)}i,
        "hxxp\\1"
      )
    end

    def safe_rm(*paths)
      paths.each do |path|
        path = Pathname(path)
        unless path.to_s.start_with?(@ctx.script_dir.to_s)
          $stderr.puts "BUG: safe_rm refusing unexpected path: #{path}"
          next
        end
        path.delete if path.exist?
      end
    end

    def branch_slug(id, type, title)
      prefix = sanitize_branch_part(type).then { |s| s.empty? ? "task" : s }
      slug   = sanitize_branch_part(title)[0, 40]
      "#{prefix}/#{id}-#{slug}"
    end

    private

    def sanitize_branch_part(str)
      str.downcase.gsub("&", "and").gsub(/[^a-z0-9]+/, "-").gsub(/\A-+|-+\z/, "")
    end

    # Uses revparse instead of branches.local, which parses `git branch -a` and
    # chokes on "* (no branch)" (detached HEAD) and "+" (branch in a linked worktree).
    def local_branch_exists?(git_repo, branch)
      git_repo.revparse("refs/heads/#{branch}")
      true
    rescue Git::FailedError
      false
    end

    # Git handle on a repo's isolated worktree, memoized per repo so a WP that
    # spans several repos opens each one once.
    #
    # The clone check lives here rather than in each command because this is the
    # funnel every git operation goes through — a check any caller could forget
    # is a check that will be forgotten.
    def worktree(repo)
      (@worktrees ||= {})[repo.name] ||= begin
        require_clone!(repo)
        Git.open(repo.worktree_host.to_s)
      end
    end

    # Fail with Harness#ensure_available!'s "start the container" message before a
    # command that will call the LLM does any work — interactive prompts, WP
    # fetches — rather than mid-run with a connection error.
    # `respond_to?` because every runner's tests inject a fake harness.
    def ensure_harness!
      @harness.ensure_available! if @harness.respond_to?(:ensure_available!)
    end

    # The tool grant for a read-only LLM phase — includes op_query when
    # OPILOT_OP_MCP is on (see MCP.md). Use ONLY at the specific call sites
    # named in that plan's Step 3 table; every other TOOLS_READ call site
    # (upstream PR review, the `create wp` draft, light one-shot passes) keeps
    # the plain constant even when the flag is on.
    def read_tools
      Harness.tools_for(Harness::TOOLS_READ, op_mcp: @ctx.op_mcp?, gh_mcp: @ctx.gh_mcp?)
    end

    # As #read_tools, for the one write-enabled call site the plan grants the
    # tool to: gh-agent's own-PR reply and CI fix. The fix implement run keeps
    # no MCP tool at all — see MCP.md's Step 3 table for why.
    def impl_tools
      Harness.tools_for(Harness::TOOLS_IMPL, op_mcp: @ctx.op_mcp?, gh_mcp: @ctx.gh_mcp?)
    end

    # One-time, best-effort report of what the instance's MCP server actually
    # offers (see MCP.md, "A startup check on what the instance really
    # offers"). Call once per process — Agent#setup, GhAgent#setup, and once at
    # the start of each `dev` verb that grants the tool — never inside
    # guarded_tick/#tick.
    #
    # It WARNS; it never raises. That is the opposite of #ensure_harness! and
    # Pull#ensure_bot_identity!, which raise on purpose because a run without a
    # model or an identity cannot work — this one has a working fallback (the
    # mirrors), so a 404, an unreachable gateway, or a malformed answer just
    # leaves op_query unused for the run.
    def report_mcp_status
      return unless @ctx.op_mcp?
      return unless Helpers.first_mcp_report?
      unless @ctx.mcp_gw_url
        log_script "OpenProject MCP: OPILOT_OP_MCP is set but OPILOT_MCP_GW_URL is not — is this running through ./opilot?"
        return
      end
      log_script "OpenProject MCP: #{Clients::OpMcp.new(@ctx.mcp_gw_url, @ctx.gw_token).summary}"
    rescue Clients::OpMcp::Unavailable
      # The common case now that OPILOT_OP_MCP defaults on: most instances have
      # no Enterprise MCP server enabled. Quiet by design — op_query itself
      # reports the same thing per call, so this is not new information, only
      # confirmation the run isn't silently broken.
      log_script "OpenProject MCP: not available on this instance — op_query will report that per call."
    rescue StandardError => e
      log_script "OpenProject MCP: startup check failed (#{e.message}) — op_query will report unavailable at call time."
    end

    # True once per process — `./opilot agent` sets up both loops.
    def self.first_mcp_report?
      return false if @op_mcp_reported
      @op_mcp_reported = true
    end

    # `./opilot` provisions the clones, but a clone whose `git clone` failed (a
    # wrong `base` in repos.json, a network blip) only WARNS and is skipped — so
    # this state is reachable, and every later stage needs the clone: it is where
    # the LLM writes, and its `.git/info/exclude` is what keeps a `pd` spec tree
    # out of unrelated commits (installed silently, so its absence says nothing).
    # Raised instead of letting Git.open surface `path does not exist`, which
    # names neither the repo nor the fix.
    def require_clone!(repo)
      return if (repo.worktree_host / ".git").exist?
      raise OPilot::FatalError, <<~MSG.strip
        No git clone for #{repo.name} at #{repo.worktree_host}.
        Run `./opilot` once to provision the clones (it warns and skips a repo whose
        clone failed — check that repo's "base" branch in repos.json), then re-run.
      MSG
    end

    # Check out the WP's fix branch in `repo`, creating it from origin/<base> on
    # first use. `checkout -b` from a remote start point makes the new branch
    # track origin/<base>, which is dangerous: a bare `git pull` merges the base
    # into the fix branch, and with push.default=upstream a bare `git push`
    # targets the base itself. Re-point tracking at the branch's own name — the
    # PR branch it is pushed to — on every checkout.
    def checkout_branch(st, repo)
      wt   = worktree(repo)
      base = st.base_for(repo)
      # Always fetch, including the default base. `./opilot` fetches it once at
      # launch, which an agent loop then outruns: a week-old process would cut
      # every new fix branch from week-old upstream. A non-default base may not be
      # in the clone at all (clones aren't --single-branch, so default-base
      # siblings exist, but a newer/less-common base needs fetching).
      fetch_base(wt, repo, base)
      if local_branch_exists?(wt, st.branch)
        wt.checkout(st.branch)
      else
        clear_leftovers!(wt, repo)
        wt.checkout(st.branch, new_branch: true, start_point: "origin/#{base}")
      end
      wt.config_set("branch.#{st.branch}.remote", "origin")
      wt.config_set("branch.#{st.branch}.merge", "refs/heads/#{st.branch}")
    end

    # Clear the clone before a NEW work branch is cut from it. Nothing else
    # removes an untracked file — not a checkout, not #sync_base! — so one an
    # earlier run left behind sits there until the next WP's `git add --all`
    # sweeps it into ITS commit (opf/openproject#24916).
    #
    # New-branch path only: an existing branch may be a run resuming after it
    # died between the LLM writing files and the commit, and that work is its own.
    #
    # Reset to HEAD, not origin/<base>: HEAD may still be a previous WP's branch,
    # and resetting to the base would rewind it. HEAD moves no ref, only the tree.
    # No `x:` — the pd spec tree is git-excluded by design, and pd cuts branches
    # through here too. Never fatal, and every discarded path is logged: a file
    # appearing from nowhere is the bug, so removing one silently repeats it.
    def clear_leftovers!(wt, repo)
      leftovers = wt.clean(force: true, d: true, dry_run: true).to_s.lines.map(&:strip).reject(&:empty?)
      leftovers.each { |line| log_script "#{repo.name}: discarding leftover — #{line}" }
      wt.reset("HEAD", hard: true)
      wt.clean(force: true, d: true)
    rescue StandardError => e
      log_script "#{repo.name}: could not clear the clone before branching (#{e.message}) — " \
                 "anything left in it may end up in this commit."
    end

    # Fetch a base branch into its remote-tracking ref (origin/<base>) so the fix
    # branch can be created from it. Read-only over the clone's public https
    # origin, so no auth — mirrors how ./opilot provisions the default base. A
    # missing branch surfaces as a clear error the runner reports on the WP.
    def fetch_base(wt, repo, base)
      wt.fetch("origin", ref: base)
    rescue StandardError => e
      raise "base branch #{base.inspect} not found on #{repo.upstream} (#{e.message})"
    end

    # Refspecs the READ phases answer questions from. #fetch_base pulls exactly
    # ONE ref — the base — so every tag and every release/* branch in a clone
    # stays as-of-clone-time, and nothing else ever updates them. That is worse
    # than it sounds: the clone still HAS a release/17.6 and a tag list to
    # compare against, so "is this commit in 17.6?" gets a confident answer off
    # a months-old snapshot, with nothing in the tree saying so.
    #
    # Narrow on purpose. Fetching every head would put the openproject
    # monorepo's full branch list on every plan and chat; release/* plus tags is
    # what a "has this shipped yet?" question actually reads.
    RELEASE_REFSPEC = "+refs/heads/release/*:refs/remotes/origin/release/*".freeze

    # Best-effort, unlike #fetch_base: a repo with no release/* namespace is
    # normal (a glob refspec matching nothing is not an error to git), and a
    # stale tag beats a failed chat. Only the READ path calls this —
    # #checkout_branch needs the base and nothing else, and would pay the cost
    # on every implement run for nothing.
    def fetch_read_refs(wt, repo)
      wt.fetch("origin", ref: RELEASE_REFSPEC, tags: true)
    rescue StandardError => e
      log_script "#{repo.name}: could not refresh tags and release branches (#{e.message}) — " \
                 "answers about tags and releases may be stale."
    end

    # Point `repo`'s clone at current upstream before a READ-ONLY phase (plan,
    # chat). Nothing else does: `./opilot` fetches each base once at launch
    # without moving the tree, and no run checks the tree back off its fix branch
    # — so a plan would otherwise be written against the original clone commit,
    # or against another WP's leftover branch, with nothing in the tree saying so.
    # Tags and release/* come along too (#fetch_read_refs) — the read phases are
    # asked about them, and no other code path fetches them at all.
    #
    # Detached at origin/<base>, since a local base branch would be a second thing
    # to keep in sync; #checkout_branch cuts fix branches from origin/<base>
    # regardless of HEAD. Never fatal — a stale answer beats no answer. A DIRTY
    # tree is left strictly alone: it means an implement run died after the LLM
    # wrote files but before #commit, and a checkout would discard that work.
    def sync_base!(repo)
      wt = worktree(repo)
      if dirty_worktree?(wt)
        log_script "#{repo.name}: uncommitted changes in the clone — reading it as-is, not syncing."
        return false
      end
      fetch_base(wt, repo, repo.base)
      fetch_read_refs(wt, repo)
      wt.checkout("origin/#{repo.base}")
      true
    rescue StandardError => e
      log_script "#{repo.name}: could not sync to origin/#{repo.base} (#{e.message}) — reading the clone as-is."
      false
    end

    # Untracked files are deliberately not counted: a `pd` spec tree lives in the
    # clone untracked-and-git-excluded by design, and the LLM's own scratch output
    # would otherwise pin the tree to a stale commit forever.
    def dirty_worktree?(wt)
      st = wt.status
      st.changed.any? || st.added.any? || st.deleted.any?
    end

    # Sync every clone the LLM is about to read. One log line for the set, since
    # #sync_base! already reports the cases worth seeing (dirty tree, fetch
    # failure) and a per-repo "ok" on a whole-registry plan is just noise.
    def sync_bases_for_reading(repos)
      list = Array(repos)
      return if list.empty?
      log_script "Syncing #{list.length} clone#{list.length == 1 ? "" : "s"} to current upstream"
      list.each { |repo| sync_base!(repo) }
    end

    # Check out an existing PR's branch in `repo` and sync it to the PR's current
    # head. Unlike #checkout_branch (which starts new work from origin/<base>),
    # gh-agent acts on a branch that already lives on the remote. The caller must
    # first fetch that head into FETCH_HEAD over HTTPS (Clients::GitHub#fetch_branch)
    # — we then hard-reset onto FETCH_HEAD, building on the latest PR head and
    # never diverging. We reset to FETCH_HEAD rather than a remote-tracking ref so
    # this works without relying on the worktree's `origin` (which may be SSH and
    # unreachable in the container).
    def checkout_pr_branch(repo, branch)
      wt = worktree(repo)
      if local_branch_exists?(wt, branch)
        wt.checkout(branch)
        wt.reset("FETCH_HEAD", hard: true)
      else
        wt.checkout(branch, new_branch: true, start_point: "FETCH_HEAD")
      end
    end

    def record_progress(id, branch, note)
      @ctx.progress_file.open("a") do |f|
        f.puts "#{Time.now.strftime("%Y-%m-%dT%H:%M")}|#{id}|#{branch}|#{note}"
      end
    end

    # Build the ItemState for a WP, creating its work_packages/<host>/<id>/ directory. The
    # target repos are loaded from target_repos.json (set once the LLM picks them
    # in the plan); until then the state defaults to the registry's default repo.
    def state_for(item_id, subject, type = nil)
      dir = Helpers.item_dir(@ctx, item_id)
      dir.mkpath
      ItemState.new(
        item_id:           item_id.to_s,
        subject:           subject.to_s,
        branch:            branch_slug(item_id, type.to_s, subject.to_s),
        repos:             target_repos_for(item_id),
        bases:             target_bases_for(item_id),
        item_dir:          dir,
        plan_file:         dir / "plan.md",
        item_file:         dir / "item.json",
        related_file:      dir / "related.json",
        target_repos_file: dir / "target_repos.json",
        target_base_file:  dir / "target_base.json",
        # The implementation options offered for this WP, written when a `ship`
        # plan call answers with the OPTIONS sentinel. Present means "opilot is
        # waiting for a number"; a chosen option leaves it in place, so the
        # reporter can read the list again after the prototype exists.
        options_file:      dir / "options.json",
        # Work packages `@opilot create wp` has already created FROM this one,
        # keyed by the trigger comment's timestamp. Written the moment a POST
        # succeeds: a work package can never be deleted, so a re-fired trigger
        # must find the record rather than create a second work package.
        created_wps_file:  dir / "created_wps.json",
        session_file:      dir / "session_id"
      )
    end

    # The Repo objects a WP targets, read from <id>/target_repos.json (an
    # array of registry names); unknown names are dropped and an empty/missing
    # file falls back to the registry default, so single-repo flows just work.
    def target_repos_for(item_id)
      file  = Helpers.item_dir(@ctx, item_id) / "target_repos.json"
      names = Helpers.safe_json_read(file) if file.exist?
      repos = Array(names).filter_map { |n| @ctx.repos[n] }
      repos.empty? ? [@ctx.default_repo] : repos
    end

    # The per-repo base overrides a WP requested, read from
    # <id>/target_base.json ({ "<repo>" => "<base>" }); empty/missing means
    # every repo uses its registry default base.
    def target_bases_for(item_id)
      file = Helpers.item_dir(@ctx, item_id) / "target_base.json"
      (file.exist? ? Helpers.safe_json_read(file) : nil) || {}
    end

    # Persist the repos the LLM chose for a WP (validated against the registry) and
    # update the live state. Names not in the registry are ignored; if none
    # survive, the default repo is used so a fix still ships somewhere. `bases` is
    # a { name => base } map of the per-repo base overrides the LLM declared (via
    # the REPOS `name@base` syntax); it is kept only for valid, chosen repos.
    def set_target_repos(st, names, bases = {})
      repos = Array(names).filter_map { |n| @ctx.repos[n.to_s.strip] }.uniq(&:name)
      repos = [@ctx.default_repo] if repos.empty?
      st.target_repos_file.write(JSON.generate(repos.map(&:name)))
      st.repos = repos

      chosen = repos.map(&:name)
      overrides = (bases || {}).filter_map do |name, base|
        n = name.to_s.strip
        b = base.to_s.strip
        [n, b] if chosen.include?(n) && !b.empty?
      end.to_h
      if overrides.empty?
        safe_rm(st.target_base_file)
      else
        st.target_base_file.write(JSON.generate(overrides))
      end
      st.bases = overrides
    end

    # Rewrite a host path under .opilot/ to its path inside the harness container.
    def container_path(host_path)
      Helpers.state_container_path(@ctx, host_path)
    end

    # Rewrite a host path inside a repo's worktree to its /repos/<name> path
    # inside the harness container.
    def container_path_for(repo, host_path)
      host_path.to_s.sub(repo.worktree_host.to_s, repo.worktree_container)
    end

    # Fetch a WP's related work packages (relations + parent/children) via the
    # injected @pull, write the index to related.json, and return its container
    # path — or nil when there are none, so the prompt omits the RELATED section.
    # Each related WP is also cached to its own item.json (by @pull) so the LLM can
    # read the full detail on demand via the item_path in the index. Shared by the
    # op-agent (Agent) and the terminal fix/plan flow (FixRunner).
    def related_ref(st)
      related = @pull.related_work_packages(st.item_id)
      return nil if related.empty?
      indexed = related.map do |r|
        r.merge("item_path" => container_path(Helpers.item_dir(@ctx, r["id"]) / "item.json"))
      end
      st.related_file.write(JSON.generate(indexed))
      container_path(st.related_file)
    end

    # Shape Repo objects for a prompt's repo listing — name, container path (where
    # the LLM reads/edits the files), and the one-line description.
    def repos_for_prompt(repos)
      repos.map { |r| { name: r.name, path: r.worktree_container, description: r.description } }
    end

    # Read the `REPOS:` line the LLM put at the top of a fresh plan, validate the
    # names against the registry, record the chosen repos, and strip the line from
    # the saved plan. Falls back to the default repo when the line is absent or
    # names nothing valid (so single-repo plans need no REPOS line).
    def record_chosen_repos(st)
      text    = st.plan_file.read
      m       = text.match(/^[ \t]*REPOS:[ \t]*(.+?)[ \t]*$/i)
      entries = m ? m[1].split(",").map(&:strip).reject(&:empty?) : []
      # Each entry is "<name>" or "<name>@<base>"; split on the first @ so a base
      # like "release/17.6" survives intact.
      names = []
      bases = {}
      entries.each do |entry|
        name, base = entry.split("@", 2).map(&:strip)
        next if name.to_s.empty?
        names << name
        bases[name] = base if base && !base.empty?
      end
      set_target_repos(st, names, bases)
      st.plan_file.write(text.sub(/^[ \t]*REPOS:.*\R?/i, "")) if m
    end

    def branch_has_commits?(st, repo)
      worktree(repo).log.between("origin/#{st.base_for(repo)}", st.branch).execute.any?
    end

    # True when a phase will resume an existing per-WP session (so the plan and
    # issue are already in context). False for a fresh session — e.g. the first
    # call, or after the session was cleared — where the prompt must tell the LLM
    # to read the plan instead of assuming it.
    def session_resumable?(st)
      Helpers.file_has_content?(st.session_file)
    end

    # Stage everything in `wt` and return the diff, or nil when there is nothing
    # to commit. Prints the per-file stat lines, which a caller always wants
    # immediately before committing. This is the one definition of "did the LLM
    # change anything?", and it hands the diff back rather than making a caller
    # that needs to describe it take a second one.
    def stage_all(wt)
      wt.add(all: true)
      diff = wt.diff("HEAD")
      return nil if diff.entries.empty?
      diff.stats[:files].each { |f, s| puts "  #{f} | +#{s[:insertions]} -#{s[:deletions]}" }
      diff
    end

    # Commit the staged tree and report the commit in one format everywhere.
    # `where` names the repo when a run spans several of them; a single-repo
    # context leaves it off.
    def commit_and_log(wt, message, where = nil)
      wt.commit(message)
      c = wt.log(1).execute.first
      log_script "Committed#{where ? " to #{where}" : ""}: #{c.sha[0, 7]} #{c.message}"
      c
    end

    # Check out the fix branch in every target repo, implement the plan once
    # across all their worktrees, and commit per repo. Returns the repos that
    # ended up with commits — [] when the plan turned out to be a no-op.
    #
    # One implementation pass covers every repo: the planning session is resumed,
    # so it carries its exploration in and the write tools are simply added. The
    # whole step is skipped when every fix branch already holds commits (an
    # earlier `dev commit`, or a re-run), so publishing then costs no LLM call.
    #
    # Reporting the result is deliberately left to the caller — a work-package
    # comment and a console line are not the same message.
    def implement_plan(st, model: Harness::MODEL_HEAVY)
      st.repos.each { |r| checkout_branch(st, r) }

      unless st.repos.all? { |r| branch_has_commits?(st, r) }
        log_script "Implementing #{wp_label(st.item_id)} in #{st.repos.map(&:name).join(", ")}"
        @harness.run(
          Prompts.implement(repos: repos_for_prompt(st.repos), plan: container_path(st.plan_file),
                            resumed: session_resumable?(st)),
          tools: Harness::TOOLS_IMPL, model: model, session_file: st.session_file
        )
        st.repos.each { |r| commit(st, r) }
      end

      st.repos.select { |r| branch_has_commits?(st, r) }
    end

    # Commit the worktree changes for one repo. Returns true when a commit was
    # made, false when this repo had no changes (so the caller can skip its PR).
    def commit(st, repo)
      Helpers.adopt_github_author!(@publish.author_token)
      wt = worktree(repo)
      return false unless stage_all(wt)
      commit_and_log(wt, pr_title(st.item_id, st.subject), repo.name)
      record_progress(st.item_id, st.branch, "committed:#{repo.name}")
      true
    end

    # Ask a cheap model for a one-line commit subject from the diff (stateless —
    # no session to resume), then sanitise it to a single bare line. Returns ""
    # on any failure so the caller can fall back to a generic subject. Shared by
    # gh-agent's follow-up commits and the terminal `pr` refresh.
    def generate_commit_subject(diff)
      prompt = Prompts.commit_subject(diff: diff.patch.to_s[0, 6000])
      reply = @harness.run(prompt, tools: Harness::TOOLS_READ, model: Harness::MODEL_LIGHT)
      strip_ansi(reply.to_s).lines.map(&:strip).find { |l| !l.empty? }.to_s
        .gsub(/\A["'`]+|["'`]+\z/, "")   # strip wrapping quotes/backticks
        .sub(/\A\[[^\]]*\]\s*/, "")       # drop any "[label]" the LLM prepended anyway
        .gsub(/\s+/, " ")
        .slice(0, 72).to_s.strip
    rescue => e
      log_script "Commit-subject generation failed: #{e.message}"
      ""
    end

    # Stateless — a fresh, cheap-model call rather than a resumed session, since
    # the item/plan/diff are all passed as file paths or plain text the model can
    # read itself, with nothing depending on the implement session's history.
    def generate_pr_description(st, repo, model: Harness::MODEL_LIGHT)
      pr_desc_file = st.pr_desc_file(repo)
      return if Helpers.file_has_content?(pr_desc_file)
      wt               = worktree(repo)
      template_file    = repo.worktree_host / ".github" / "pull_request_template.md"
      template_section = template_file.exist? ? "Fill in this PR template exactly: #{container_path_for(repo, template_file)}" : ""
      diff_stat = wt.diff("HEAD~1", "HEAD").stats[:files]
        .map { |f, s| "  #{f} | +#{s[:insertions]} -#{s[:deletions]}" }
        .join("\n")
      prompt = Prompts.pr_description(
        item: container_path(st.item_file), plan: container_path(st.plan_file),
        diff_stat: diff_stat, template_section: template_section
      )
      pr_text = @harness.run(prompt, tools: Harness::TOOLS_READ, model: model)
      pr_body = pr_text[/^#.*/m] || pr_text
      pr_desc_file.write(strip_ansi(pr_body))
    end
  end
end
